### ISSUE TITLE
Help with the script

### ISSUE THREAD

**Issue by Flaam** [danielkrupinski/MemJect#1]
Hi Daniel, probably this is not the right page to ask help, but, how can i use the script? I can open the solution on VS and i have already downloaded Python but what i need to do before opening the script? If you can send me some imgur screens. Thank you

**Comment by danielkrupinski** [comment]
What script you refer to?

**Comment by Flaam** [comment]
@danielkrupinski https://github.com/danielkrupinski/PE2HEX

**Comment by danielkrupinski** [comment]
Drag and drop dll file onto the script.

**Comment by Flaam** [comment]
@danielkrupinski ok thanks
