### ISSUE TITLE
PE Header Erase

### ISSUE THREAD

**Issue by 0xE232FE** [danielkrupinski/MemJect#4]
1st Question
There are two Methods which Zero's the Memory, they are both equal but besides the Secure one Zero's the Memory even the Compile Optimization removes the Function. Why don't use the Secure Version?

RtlSecureZeroMemory vs RtlZeroMemory

2nd Question
Is the AddressOfEntryPoint deleted if you Zero the PE Header completly? Or do I have to Zero the AddressOfEntryPoint seperatly?

**Comment by danielkrupinski** [comment]
1. I think compiler optimizations apply only to data known at compile time. Here it isn't, addresses to erase are known only on runtime.
2. AddressOfEntryPoint is a pointer to entry point which is located outside headers.

**Comment by Floraly** [comment]
Okay thank you very much for describing it. After I read the Microsoft Paper of PE Header I was a bit confused if the Enty Point belongs to the header or not.

**Comment by 0xE232FE** [comment]
Thank you very much for description! Appreciate it! :-)
